import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer";
import Topheader from "@/components/topheader";
import Navbar from "@/components/navbar";
import Providers from "./providers";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "E-Commerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <Providers>
        <Topheader/>
        <Navbar/>

        {children}
        <Footer/>
        </Providers>

      </body>
    </html>
    
    // <html lang="en">
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
    //     {!isStudioRoute && <Topheader />} {/* Topheader excluded for /studio */}
    //     <Providers>
    //       {!isStudioRoute && <Navbar />} {/* Navbar excluded for /studio */}
    //       {children}
    //       {!isStudioRoute && <Footer />} {/* Footer excluded for /studio */}
    //     </Providers>
    //   </body>
    // </html>
  );
}
