export const products = [
    {
        id: 1,
        image: ['/gradient.png'],
        title: 'gradient graphic t-shirt',
        rating: 3.5,
        price: 145,
        discount: 0,
        category: 't-shirts',
        slug: 'gradient-graphic-t-shirt',
        description: 'This gradient graphic t-shirt is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.',
        color: ['#4f4631', '#314F4A', '#31344F'],
        size: ['small', 'medium', 'large', 'x-large'],
        quantity: 1
    },
    {
        id: 2,
        image: ['/polo.png'],
        title: 'polo with tipping details',
        rating: 4.5,
        price: 180,
        discount: 0,
        category: 'shirts',
        slug: 'polo-with-tipping-details',
        description: 'This polo with tipping details is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.',
        color: ['#4f4631', '#314F4A', '#31344F'],
        size: ['small', 'medium', 'large', 'x-large'],
        quantity: 1
    },
    {
        id: 3,
        image: ['/blackstriped.png'],
        title: 'black striped shirt',
        rating: 5.0,
        price: 150,
        discount: 30,
        category: 't-shirts',
        slug: 'black-striped-shirt',
        description: 'This black striped shirt is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.',
        color: ['#4f4631', '#314F4A', '#31344F'],
        size: ['small', 'medium', 'large', 'x-large'],
        quantity: 1
    },
    {
        id: 4,
        image: ['/jeans.png'],
        title: 'skinny fit jeans',
        rating: 3.5,
        price: 260,
        discount: 20,
        category: 'jeans',
        slug: 'skinny-fit-jeans',
        description: 'These skinny fit jeans are perfect for any occasion. Crafted from a soft and breathable fabric, they offer superior comfort and style.',
        color: ['#4f4631', '#314F4A', '#31344F'],
        size: ['small', 'medium', 'large', 'x-large'],
        quantity: 1
    },
    {
        id: 5,
        image: ['/shirtoffice.png'],
        title: 'checkered shirt',
        rating: 4.5,
        price: 180,
        discount: 0,
        category: 'shirts',
        slug: 'checkered-shirt',
        description: 'This checkered shirt is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.',
        color: ['#4f4631', '#314F4A', '#31344F'],
        size: ['small', 'medium', 'large', 'x-large'],
        quantity: 1
    },
    {
        id: 6,
        image: ['/tshirt.png'],
        title: 'sleeve striped t-shirt',
        rating: 4.5,
        price: 160,
        discount: 30,
        category: 't-shirts',
        slug: 'sleeve-striped-t-shirt',
        description: 'This sleeve striped t-shirt is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.',
        color: ['#4f4631', '#314F4A', '#31344F'],
        size: ['small', 'medium', 'large', 'x-large'],
        quantity: 1
    },
    {
        id: 7,
        image: ['/vertical.png'],
        title: 'vertical striped shirt',
        rating: 5.0,
        price: 232,
        discount: 20,
        category: 'shirts',
        slug: 'vertical-striped-shirt',
        description: 'This vertical striped shirt is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.',
        color: ['#4f4631', '#314F4A', '#31344F'],
        size: ['small', 'medium', 'large', 'x-large'],
        quantity: 1
    },
    {
        id: 8,
        image: ['/graphic.png'],
        title: 'courage graphic t-shirt',
        rating: 4.0,
        price: 145,
        discount: 0,
        category: 't-shirts',
        slug: 'courage-graphic-t-shirt',
        description: 'This courage graphic t-shirt is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.',
        color: ['#4f4631', '#314F4A', '#31344F'],
        size: ['small', 'medium', 'large', 'x-large'],
        quantity: 1
    },
    {
        id: 9,
        image: ['/bermuda.png'],
        title: 'loose fit bermuda shorts',
        rating: 3.0,
        price: 80,
        discount: 0,
        category: 'shorts',
        slug: 'loose-fit-bermuda-shorts',
        description: 'These loose fit bermuda shorts are perfect for any occasion. Crafted from a soft and breathable fabric, they offer superior comfort and style.',
        color: ['#4f4631', '#314F4A', '#31344F'],
        size: ['small', 'medium', 'large', 'x-large'],
        quantity: 1
    },
    {
        id: 10,
        image: ['/polocontrast.png'],
        title: 'polo with contrast trims',
        rating: 4.0,
        price: 242,
        discount: 20,
        category: 'shirts',
        slug: 'polo-with-contrast-trims',
        description: 'This polo with contrast trims is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.',
        color: ['#4f4631', '#314F4A', '#31344F'],
        size: ['small', 'medium', 'large', 'x-large'],
        quantity: 1
    },
    {
        id: 11,
        image: ['/faded.png'],
        title: 'faded skinny jeans',
        rating: 4.5,
        price: 210,
        discount: 0,
        category: 'jeans',
        slug: 'faded-skinny-jeans',
        description: 'These faded skinny jeans are perfect for any occasion. Crafted from a soft and breathable fabric, they offer superior comfort and style.',
        color: ['#4f4631', '#314F4A', '#31344F'],
        size: ['small', 'medium', 'large', 'x-large'],
        quantity: 1
    },
    {
        id: 12,
        image: ['/shirtoff.png'],
        title: 't-shirt with tape details',
        rating: 4.5,
        price: 120,
        discount: 0,
        category: 't-shirts',
        slug: 't-shirt-with-tape-details',
        description: 'This t-shirt with tape details is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.',
        color: ['#4f4631', '#314F4A', '#31344F'],
        size: ['small', 'medium', 'large', 'x-large'],
        quantity: 1
    },
];
